# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6cb763d2c7a56495020ae297f36e7d94afccdbb2b38703f9bcf810ca724e002f55867efd7ad4b72dbe44356e691611adcfcd7258891d14098ddc919def10b0f

test:
  secret_key_base: dde3d8984b312280524e3cb9c0fd5e89a820e906bb810de4e8572166eecd5ed9465017b4aa954098182c0184a6158d6931a98d1a4b3363a4186a99ba8ba0ea18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
